export * from './fleet.service';
import { FleetService } from './fleet.service';
export * from './notes.service';
import { NotesService } from './notes.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './samples.service';
import { SamplesService } from './samples.service';
export * from './security.service';
import { SecurityService } from './security.service';
export * from './token.service';
import { TokenService } from './token.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './values.service';
import { ValuesService } from './values.service';
export * from './vehicles.service';
import { VehiclesService } from './vehicles.service';
export const APIS = [FleetService, NotesService, ProductsService, SamplesService, SecurityService, TokenService, UsersService, ValuesService, VehiclesService];
